### ISSUE TITLE
`kart import --list-formats` raises error

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/kart#427]
```
Kart v0.9.1.dev0+ci.2237.git0e0a8ed3, Copyright (c) Kart Contributors
» GDAL v3.2.0; PROJ v6.3.0
» PyGit2 v1.3.0; Libgit2 v1.1.0; Git v2.31.1
» SQLAlchemy v1.4.11; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.0; Libpq v13.0.2
» SpatialIndex v1.9.3
```

`kart import --list-formats` is (I think) intended to list intended import formats, however it currently raises the following error:

```
$ kart import --list-formats
Traceback (most recent call last):
  File "kart_cli.py", line 4, in <module>
  File "kart/cli.py", line 333, in entrypoint
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "kart/cli.py", line 157, in invoke
  File "click/core.py", line 1257, in invoke
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "kart/cli_util.py", line 240, in actual_callback
TypeError: list_import_formats() missing 2 required positional arguments: 'param' and 'value'
[79976] Failed to execute script kart_cli
```

**Comment by olsen232** [comment]
Fixed at 9cf4376bb555ef51c13bf5e93f0fe08d656648f8
