### ISSUE TITLE
0.10rc2: imported tree has both `.sno-dataset` and `.table-dataset` trees

### ISSUE THREAD

**Issue by craigds** [koordinates/kart#443]
I imported a fresh repo from postgres using 0.10.0rc2, and it seems a bit broken; the dataset has a `.sno-dataset` tree _and_ a `.table-dataset` tree. All the blobs are contained in the `.table-dataset` tree, and `.sno-dataset` contains only an empty `meta` tree:

```
$ git ls-tree HEAD tiny_layer_with_several_revisions/
040000 tree c25900a0ccb08d0ea7224a15be65e5c857c1e98d	tiny_layer_with_several_revisions/.sno-dataset
040000 tree aa80b12065639a31151150a8cb540f447f6e450d	tiny_layer_with_several_revisions/.table-dataset

$ git ls-tree HEAD tiny_layer_with_several_revisions/.sno-dataset/
040000 tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904	tiny_layer_with_several_revisions/.sno-dataset/meta

$ git ls-tree HEAD tiny_layer_with_several_revisions/.sno-dataset/meta/
(empty)

```

On later inspection using `kart show`, kart crashes because the presence of `.sno-dataset` makes it look in the wrong place for `schema.json`, and it can't find it:

```
$ kart show
commit 187762d447357a50624735733d580b5fd1de407c
Author: kx <support@koordinates.com>
Date:   Wed May  8 04:18:24 2019 +0000

    .

Traceback (most recent call last):
  File "/usr/local/bin/kart", line 33, in <module>
    sys.exit(load_entry_point('kart', 'console_scripts', 'kart')())
  File "/Users/cdestigter/checkout/kart/kart/cli.py", line 334, in entrypoint
    cli()
  File "/Users/cdestigter/checkout/kart/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cdestigter/checkout/kart/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cdestigter/checkout/kart/kart/cli.py", line 158, in invoke
    return super().invoke(ctx)
  File "/Users/cdestigter/checkout/kart/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cdestigter/checkout/kart/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cdestigter/checkout/kart/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cdestigter/checkout/kart/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cdestigter/checkout/kart/kart/show.py", line 46, in show
    json_style=json_style,
  File "/Users/cdestigter/checkout/kart/kart/diff.py", line 219, in diff_with_writer
    w(ds, diff)
  File "/Users/cdestigter/checkout/kart/kart/diff_output.py", line 102, in _out
    pk_field = dataset.primary_key
  File "/Users/cdestigter/checkout/kart/kart/base_dataset.py", line 196, in primary_key
    if len(self.schema.pk_columns) == 1:
  File "/Users/cdestigter/checkout/kart/kart/import_source.py", line 137, in schema
    self._schema = self._init_schema()
  File "/Users/cdestigter/checkout/kart/kart/import_source.py", line 149, in _init_schema
    return Schema.from_column_dicts(self.get_meta_item("schema.json"))
  File "/Users/cdestigter/checkout/kart/kart/schema.py", line 261, in from_column_dicts
    columns = [ColumnSchema.from_dict(d) for d in column_dicts]
TypeError: 'NoneType' object is not iterable
```

I'm sure there is a fix that involves not creating the bogus empty tree, but probably we should just avoid Dataset3 having any code for `.sno-dataset` at all (that code can live only in dataset2)

**Comment by craigds** [comment]
Found it; this was actually caused by some external hackery I was doing outside of Kart, to add extra files using `kart commit-files --amend`. It was creating empty files in the old meta tree and thus observing this problem. It isn't a kart bug.
