### ISSUE TITLE
Kart throws "ValueError: 1006 is not a valid GeometryType"

### ISSUE THREAD

**Issue by AsgerPetersen** [koordinates/kart#483]
After editing a feature from this repo https://github.com/AsgerPetersen/kart-test using QGIS I get the following error when i run `kart diff`:

```
❯ kart diff
--- skov:feature:95748
+++ skov:feature:95748
ValueError: 1006 is not a valid GeometryType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kart_cli.py", line 4, in <module>
  File "kart/cli.py", line 335, in entrypoint
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "kart/cli.py", line 158, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "kart/diff.py", line 145, in diff
  File "kart/base_diff_writer.py", line 219, in write_diff
  File "kart/base_diff_writer.py", line 226, in write_ds_diff_for_path
  File "kart/text_diff_writer.py", line 66, in write_ds_diff
  File "kart/text_diff_writer.py", line 141, in write_feature_delta
  File "kart/feature_output.py", line 22, in feature_field_as_text
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 310, in __call__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 564, in __new__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 548, in __new__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 577, in _missing_
ValueError: 1006 is not a valid GeometryType
[43303] Failed to execute script kart_cli
```

PS. this project looks really promising! Thank you for sharing it with the rest of us!

**Comment by rcoup** [comment]
Thanks @AsgerPetersen — I've managed to reproduce it here, and I'll try and get a fix for you asap

**Comment by rcoup** [comment]
Hi @AsgerPetersen, if you download an installer from https://github.com/koordinates/kart/actions/runs/1294370030 (scroll to the bottom and choose Linux/Windows/macOS-* as appropriate) the issue should be fixed. Thanks for your bug report!

**Comment by AsgerPetersen** [comment]
Thank you very much!
