### ISSUE TITLE
kart commit --allow-empty fails on an empty repo

### ISSUE THREAD

**Issue by pfw** [koordinates/kart#640]
**Describe the bug**
kart commit --allow-empty fails on an empty repo

**To Reproduce**
```kart init `pwd`/one```
```cd `pwd`/one```
```kart commit --allow-empty```

**Expected behaviour**
No traceback

**Output**
```
Traceback (most recent call last):
  File "kart_cli.py", line 4, in <module>
  File "kart/cli.py", line 351, in entrypoint
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "kart/cli.py", line 159, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "kart/commit.py", line 135, in commit
AttributeError: 'NoneType' object has no attribute 'tree'
[51206] Failed to execute script kart_cli
```

**Version Info**
 - OS: 
```Darwin Kernel Version 21.5.0```
 - Version: 
```Kart v0.11.1, Copyright (c) Kart Contributors
» GDAL v3.3.2; PROJ v6.3.0
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.33.GIT
» SQLAlchemy v1.4.29; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v14.0.2
» SpatialIndex v1.9.3
```

**Comment by olsen232** [comment]
This was accidentally fixed as a side effect of ff4e258681efd98e2dff34d345fa72549162eede.
The output is now:
```
Error: Empty repository.
  (use "kart import" to add some data)
```
Which seems fair enough.
