### ISSUE TITLE
Unhandled exception on import of SHP where no SHX is present.

### ISSUE THREAD

**Issue by pfw** [koordinates/kart#742]
**Describe the bug**
If `kart import` is called with a shp file and there is no shx file present, kart throws a 'FOREIGN KEY constraint failed' when importing after following the advice given on the first attempt.

**To Reproduce**
Steps to reproduce the behaviour:
1. `kart init`
2.
```
❯ kart import POA_2016_AUST.shp 
Error: 'POA_2016_AUST.shp' doesn't appear to be valid (tried formats: GPKG,PG,SHP)
Unable to open POA_2016_AUST.shx or POA_2016_AUST.SHX. Set SHAPE_RESTORE_SHX config option to YES to restore or create it.
```
4. `SHAPE_RESTORE_SHX=yes kart import POA_2016_AUST.shp`
5. See error

**Expected behaviour**
Not a traceback - kart should throw a meaningful error.

`.shx`, `.shp` and `.dbf` are all [mandatory](https://en.wikipedia.org/wiki/Shapefile#Overview) in a shapefile - we shouldn't try to fix this situation but we should error out with a user friendly error text, e.g.:

```
Import source was missing some required files: {filename}.shx
```

**Output**
```
Starting git-fast-import...
Importing 2,670 features from PkGeneratingTableImportSource(POA_2016_AUST.shp:POA_2016_AUST) to POA_2016_AUST/ ...
Added 2,670 Features to index in 4.0s
Overall rate: 662 features/s)
Closed in 0s
Creating GPKG working copy at test1.gpkg ...
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1901, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
pysqlite3.dbapi2.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kart_cli.py", line 4, in <module>
  File "kart/cli.py", line 385, in entrypoint
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "kart/cli_util.py", line 69, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "kart/tabular/import_.py", line 350, in import_
  File "kart/working_copy.py", line 262, in reset_to_head
  File "kart/working_copy.py", line 299, in reset
  File "kart/working_copy.py", line 192, in create_parts_if_missing
  File "kart/tabular/working_copy/base.py", line 1272, in reset
  File "kart/tabular/working_copy/base.py", line 938, in write_full
  File "kart/tabular/working_copy/gpkg.py", line 266, in _write_meta
  File "sqlalchemy/orm/session.py", line 1714, in execute
  File "sqlalchemy/engine/base.py", line 1705, in _execute_20
  File "sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1944, in _execute_context
  File "sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 210, in raise_
  File "sqlalchemy/engine/base.py", line 1901, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlalchemy.exc.IntegrityError: (pysqlite3.dbapi2.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT OR REPLACE INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('POA_2016_AUST', 'geom', 'MULTIPOLYGON', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[6966] Failed to execute script 'kart_cli' due to unhandled exception!
```

**Version Info**
```
❯ kart --version
Kart v0.11.6.dev0, Copyright (c) Kart Contributors
» GDAL v3.4.0; PROJ v6.3.0
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.33.GIT
» SQLAlchemy v1.4.44; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v14.0.4
```

**Comment by pfw** [comment]
The process also leaves in place a .gpkg file with no contents and the repo thinks the file was imported.

```
❯ kart log              
commit 94c51dd03ca535d87f9318316450be5c32cd07cf (HEAD -> main)
Author: user <user@user.use>
Date:   Thu Dec 1 11:28:11 2022 +1100

    Import from POA_2016_AUST.shp:POA_2016_AUST to POA_2016_AUST/

```

**Comment by pfw** [comment]
As expected a clone fails as it tries to write the working copy

```
❯ kart clone test1 test1-clone
Cloning into '/Users/pfw/tmp/repos/test1-clone/.clone'...
done.
Creating GPKG working copy at test1-clone.gpkg ...
Writing features for dataset 1 of 1: POA_2016_AUST
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1901, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
pysqlite3.dbapi2.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kart_cli.py", line 4, in <module>
  File "kart/cli.py", line 385, in entrypoint
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "kart/cli_util.py", line 69, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "kart/clone.py", line 192, in clone
  File "kart/working_copy.py", line 262, in reset_to_head
  File "kart/working_copy.py", line 299, in reset
  File "kart/working_copy.py", line 192, in create_parts_if_missing
  File "kart/tabular/working_copy/base.py", line 1273, in reset
  File "kart/tabular/working_copy/base.py", line 939, in write_full
  File "kart/tabular/working_copy/gpkg.py", line 266, in _write_meta
  File "sqlalchemy/orm/session.py", line 1714, in execute
  File "sqlalchemy/engine/base.py", line 1705, in _execute_20
  File "sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1944, in _execute_context
  File "sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 210, in raise_
  File "sqlalchemy/engine/base.py", line 1901, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlalchemy.exc.IntegrityError: (pysqlite3.dbapi2.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT OR REPLACE INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('POA_2016_AUST', 'geom', 'MULTIPOLYGON', 0, 0, 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[10784] Failed to execute script 'kart_cli' due to unhandled exception!
```
