### ISSUE TITLE
subprocess.CalledProcessError: Command '['pdal', '--version']' died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by nyalldawson** [koordinates/kart#826]
**Describe the bug**
Running "kart --version" results in a segfault on Fedora 37, with the output:

```
Kart v0.12.2, Copyright (c) Kart Contributors
kart helper: unhandled exception
Traceback (most recent call last):
  File "kart/helper.py", line 236, in helper
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1054, in main
  File "click/core.py", line 920, in make_context
  File "click/core.py", line 1613, in parse_args
  File "click/core.py", line 1378, in parse_args
  File "click/core.py", line 2360, in handle_parse_result
  File "click/core.py", line 2322, in process_value
  File "kart/cli_util.py", line 403, in actual_callback
  File "kart/cli.py", line 115, in print_version
  File "subprocess.py", line 420, in check_output
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['pdal', '--version']' died with <Signals.SIGSEGV: 11>.
```

(For reference, `pdal --version` doesn't crash -- it outputs:

```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.4.3 (git-version: Release)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```)


This breaks the QGIS plugin, as it intreprets the segfault as a missing kart executable
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Install kart on fedora 37
2. Run "kart --version"

**Comment by rcoup** [comment]
mmm, works for me under arm64:

```console
$ docker run --rm -it -v $(pwd):/mnt fedora:37
[root@907b2c2dd5d4 /]# yum install -y /mnt/kart-0.12.2-1.aarch64.rpm
...
[root@907b2c2dd5d4 /]# kart --version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4
Executed via helper, PID: 85
```

I did get a similar error under amd64 though:
```console
$ docker run --rm -it --platform=linux/amd64 -v $(pwd):/mnt fedora:37
[root@192dd063833d /]# yum install -y /mnt/kart-0.12.2-1.x86_64.rpm
...
[root@192dd063833d /]# kart --version
Kart v0.12.2, Copyright (c) Kart Contributors
kart helper: unhandled exception
Traceback (most recent call last):
  File "kart/helper.py", line 236, in helper
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1054, in main
  File "click/core.py", line 920, in make_context
  File "click/core.py", line 1613, in parse_args
  File "click/core.py", line 1378, in parse_args
  File "click/core.py", line 2360, in handle_parse_result
  File "click/core.py", line 2322, in process_value
  File "kart/cli_util.py", line 403, in actual_callback
  File "kart/cli.py", line 101, in print_version
  File "subprocess.py", line 420, in check_output
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['git', '--version']' returned non-zero exit status 127.
[root@192dd063833d /]# /opt/kart/git --version
/opt/kart/git: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory
[root@192dd063833d /]# /opt/kart/pdal --version
/opt/kart/pdal: error while loading shared libraries: lib: cannot open shared object file: No such file or directory
```

Can you try with the rpm from the [latest master build](https://github.com/koordinates/kart/actions?query=is%3Asuccess+branch%3Amaster) and see if that helps at all? 

Otherwise, does `/opt/kart/pdal --version` work or return an error?
