### ISSUE TITLE
[macos] Broken build - libltdl.7.dylib

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#904]
macOS build has been broken on CI lately, but intermittent. 
Possibly, it depends which version of macOS the build is run on.
First observed a couple week ago - there's been many green builds since then and even a release, but yesterday I tried rerunning the same failure 3 times, and just got 3 more failures, so possibly.... failures are always re-run on the same machine? or, the bug is getting worse and more of the task runners are upgraded to a new macOS version?

See eg https://github.com/koordinates/kart/actions/runs/5994471902/job/16259281784?pr=903

Some likely fixes: to whitelist libltdl.7.dylib as a system dependency, or to help the builder find it and bundle it into the package.

Broken build output follows:

[ 88%] Vendor dependency archive assembly
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/bin/git-lfs
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/bin/pdal
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/bin/git
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/libexec/git-core/git-imap-send
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/libexec/git-core/git-sh-i18n--envsubst
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/libexec/git-core/git-daemon
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/libexec/git-core/git-remote-http
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/libexec/git-core/git-http-fetch
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/libexec/git-core/git-http-backend
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/lib/libpdal_util.15.3.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/lib/libpdalcpp.15.3.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/reflink-0.2.1-cp310-cp310-macosx_10_15_universal2.whl-contents/reflink/_backend.abi3.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/pygit2-1.12.1-cp310-cp310-macosx_10_15_universal2.whl-contents/pygit2/_libgit2.abi3.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/pygit2-1.12.1-cp310-cp310-macosx_10_15_universal2.whl-contents/pygit2/_pygit2.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/cffi-1.15.1-cp310-cp310-macosx_10_15_universal2.whl-contents/_cffi_backend.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/pyodbc-4.0.32-cp310-cp310-macosx_10_15_universal2.whl-contents/pyodbc.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/GDAL-3.6.3-cp310-cp310-macosx_10_15_universal2.whl-contents/osgeo/_ogr.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/GDAL-3.6.3-cp310-cp310-macosx_10_15_universal2.whl-contents/osgeo/_gnm.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/GDAL-3.6.3-cp310-cp310-macosx_10_15_universal2.whl-contents/osgeo/_gdalconst.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/GDAL-3.6.3-cp310-cp310-macosx_10_15_universal2.whl-contents/osgeo/_osr.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/GDAL-3.6.3-cp310-cp310-macosx_10_15_universal2.whl-contents/osgeo/_gdal.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/cryptography-38.0.3-cp310-cp310-macosx_10_15_universal2.whl-contents/cryptography/hazmat/bindings/_openssl.abi3.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/cryptography-38.0.3-cp310-cp310-macosx_10_15_universal2.whl-contents/cryptography/hazmat/bindings/_rust.abi3.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/psycopg2-2.8.5-cp310-cp310-macosx_10_15_universal2.whl-contents/psycopg2/_psycopg.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/pysqlite3-0.4.5-cp310-cp310-macosx_10_15_universal2.whl-contents/pysqlite3/_sqlite3.cpython-310-darwin.so
  fix_unsatisfied_deps [INFO]:	👀 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif/vendor-Darwin.tar.gz-contents/env/lib/mod_spatialite.so
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libpdalcpp.15.3.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libpdal_util.15.3.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libgdal.32.3.6.3.dylib
  fix_unsatisfied_deps [INFO]:	👀 /usr/local/Cellar/pcre2/10.42/lib/libpcre2-8.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/pkgconfig/../../lib/libz.1.2.13.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/pkgconfig/../../lib/libsqlite3.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/pkgconfig/../../lib/libcurl.4.8.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/vcpkg-vendor/vcpkg/packages/libgeotiff_x64-osx/lib/libgeotiff.5.2.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libxml2.2.10.3.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libz.1.2.13.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libtiff.6.0.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libcurl.4.8.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libssl.3.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libcrypto.3.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libgit2.1.6.4.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libffi.dylib
  fix_unsatisfied_deps [INFO]:	👀 /usr/local/Cellar/unixodbc/2.3.12/lib/libodbc.2.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libpq.5.15.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libsqlite3.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libgeos_c.1.17.2.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libproj.25.9.2.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libqhull_r.8.0.2.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libjpeg.62.3.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libpng16.16.39.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libLerc.4.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libexpat.1.8.10.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libjson-c.5.2.0.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/pkgconfig/../../lib/libnghttp2.14.24.2.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/liblzma.5.4.1.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libnghttp2.14.24.2.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libpcre.dylib
  fix_unsatisfied_deps [INFO]:	👀 /Users/runner/work/kart/kart/build/vcpkg_installed/x64-osx/lib/libgeos.3.11.2.dylib
  Error: atisfied_deps [ERROR]:	❌ Checking deps: Found 1 vendor deps where the library to satisfy the dep could not be found.
  ✅ _backend.abi3.so
  ✅ _cffi_backend.cpython-310-darwin.so
  ✅ _gdal.cpython-310-darwin.so
  ✅ _gdalconst.cpython-310-darwin.so
  ✅ _gnm.cpython-310-darwin.so
  ✅ _libgit2.abi3.so
  ✅ _ogr.cpython-310-darwin.so
  ✅ _openssl.abi3.so
  ✅ _osr.cpython-310-darwin.so
  ✅ _psycopg.cpython-310-darwin.so
  ✅ _pygit2.cpython-310-darwin.so
  ✅ _rust.abi3.so
  ✅ _sqlite3.cpython-310-darwin.so
  ✅ libLerc.4.dylib
  ✅ libcrypto.3.dylib
  ✅ libcurl.4.8.0.dylib
  ✅ libexpat.1.8.10.dylib
  ✅ libffi.dylib
  ✅ libgdal.32.3.6.3.dylib
  ✅ libgeos.3.11.2.dylib
  ✅ libgeos_c.1.17.2.dylib
  ✅ libgeotiff.5.2.0.dylib
  ✅ libgit2.1.6.4.dylib
  ✅ libjpeg.62.3.0.dylib
  ✅ libjson-c.5.2.0.dylib
  ❌ @loader_path/../../../../opt/libtool/lib/libltdl.7.dylib
  ✅ liblzma.5.4.1.dylib
  ✅ libnghttp2.14.24.2.dylib
  ✅ libodbc.2.dylib
  ✅ libpcre.dylib
  ✅ libpcre2-8.0.dylib
  ✅ libpdal_util.15.3.0.dylib
  ✅ libpdalcpp.15.3.0.dylib
  ✅ libpng16.16.39.0.dylib
  ✅ libpq.5.15.dylib
  ✅ libproj.25.9.2.0.dylib
  ✅ libqhull_r.8.0.2.dylib
  ✅ libsqlite3.dylib
  ✅ libssl.3.dylib
  ✅ libtiff.6.0.0.dylib
  ✅ libxml2.2.10.3.dylib
  ✅ libz.1.2.13.dylib
  ✅ mod_spatialite.so
  ✅ pyodbc.cpython-310-darwin.so
  Copying from . to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpy79chjif ...
  Unpacking cffi-1.15.1-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking psycopg2-2.8.5-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking reflink-0.2.1-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking GDAL-3.6.3-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking pysqlite3-0.4.5-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking pygit2-1.12.1-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking cryptography-38.0.3-cp310-cp310-macosx_10_15_universal2.whl ...
  Unpacking pyodbc-4.0.32-cp310-cp310-macosx_10_15_universal2.whl ...
  make[2]: *** [vcpkg-vendor/kart-vendor.cp310-cp310-macosx_10_15_universal2.tar.gz] Error 1
  make[1]: *** [vcpkg-vendor/CMakeFiles/vendor_archive.dir/all] Error 2
  make: *** [all] Error 2
⏱ elapsed: 377.464 seconds
Error: "'/Users/runner/work/_temp/957224822/cmake-3.25.3-macos-universal/CMake.app/Contents/bin/cmake' failed with error code: '2'.
    at CMakeRunner.<anonymous> (/Users/runner/work/_actions/lukka/run-cmake/v10/dist/index.js:5405:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/lukka/run-cmake/v10/dist/index.js:5220:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: run-cmake action execution failed: 'Error: "'/Users/runner/work/_temp/957224822/cmake-3.25.3-macos-universal/CMake.app/Contents/bin/cmake' failed with error code: '2'.'

**Comment by olsen232** [comment]
Seems to be fixed by a9df9c514f9668b62ad899b3490fe0716026fb63 - if it re-breaks, will have to look into it further
